/*
  Script:      VALIDATE_INSERT_INTO_T_LU_REWARDS_OFFER_TYPE.sql
  Schema:      REWARD
  Author:      Favio Massarini
  Project:     MK-1050
  Date:        2021-02-05
  Purpose:     Validate the look up values for Six Flags offer types.
*/

DECLARE

  V_COUNT       NUMBER;  
  V_CODE	VARCHAR2(20);

BEGIN

  -- Set values
  V_CODE := 'SIXFLAGS12MMEMB';

  -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSSSNPASS';

  -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSDAYPASS';

    -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSDXDINEPASS';

    -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSANDINEPASS';

    -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSSSNDRINK';

    -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSDAYDRINK';

    -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSDAYDINE';

  -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSDAYFLASH';

  -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;

  -- Set values
  V_CODE := 'SIXFLAGSPARKING';

  -- Count values
  SELECT COUNT(1) INTO V_COUNT FROM T_LU_REWARDS_OFFER_TYPE WHERE TEMPLATE_TYPE_CODE = V_CODE;

  -- Validate
  IF V_COUNT = 1 THEN
    DBMS_OUTPUT.PUT_LINE(V_CODE || ' ROLLOUT VALIDATION SUCCEEDED!');
  ELSE
    RAISE_APPLICATION_ERROR(-20001, V_CODE || ' ROLLOUT VALIDATION FAILED!');
  END IF;
  
END;
/
