/*
  Script:      100_REWARDatOPS_MK1050_DDL_RO.sql
  Author:      Levi TAmiozzo
  Date:        01/26/2021
  Purpose:     Add new table 	T_REWARDS_SIX_FLAGS_ITEM.
			         Add new sequence SEQ_REWARDS_SIX_FLAGS_ITEM.
			   
			         Add new table 	T_REWARDS_SF_ITEM_CODE.			   
			         Add new sequence SEQ_REWARDS_SF_ITEM_CODE.
					 Add new columns T_REWARD_REDEMPTION_HISTORY
					 Add new columns T_RWRD_REDEMPTION_PENDING
*/

SET TERMOUT ON
SET ECHO Off
spool off

SET LINESIZE 80

SET SERVEROUTPUT ON SIZE 10000
WHENEVER SQLERROR EXIT ROLLBACK
column filename NEW_VAL filename1

COLUMN T_REWARDS_SIX_FLAGS_ITEM 		NEW_VAL 	_T_REWARDS_SIX_FLAGS_ITEM
COLUMN SEQ_REWARDS_SIX_FLAGS_ITEM 		NEW_VAL 	_SEQ_REWARDS_SIX_FLAGS_ITEM

COLUMN T_REWARDS_SF_ITEM_CODE 	NEW_VAL 	_T_REWARDS_SF_ITEM_CODE
COLUMN SEQ_REWARDS_SF_ITEM_CODE 	NEW_VAL 	_SEQ_RWRDS_SF_ITEM_CODE

COLUMN ALTER_T_RWRD_RED_HISTORY NEW_VAL 	_ALTER_T_RWRD_RED_HISTORY
COLUMN ALTER_T_REWARD_RED_PENDING NEW_VAL 	_ALTER_T_REWARD_RED_PENDING

COLUMN T_LU_REWARDS_OFFER_TYPE 			NEW_VAL 	_T_LU_REWARDS_OFFER_TYPE
COLUMN SEQ_LU_REWARDS_OFFER_TYPE 		NEW_VAL 	_SEQ_LU_REWARDS_OFFER_TYPE

SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME')     filename
  FROM dual; 
  
spool empty.sql

spool  100_REWARDatOPS_MK1050_DDL_RO_&filename1..log

ALTER SESSION SET CURRENT_SCHEMA = REWARD;
ALTER SESSION SET EDITION = ORA$BASE;
 
SELECT 'current user is ' || USER || ' at '
  FROM dual;

SELECT TO_CHAR(SYSDATE, 'DD-Mon-YYYY HH24:MI:SS') date_
  FROM dual;

-- Check Table for Six Flags Item
SELECT CASE WHEN MAX(TABLE_NAME) IS NULL THEN 'T_REWARDS_SIX_FLAGS_ITEM.sql' ELSE 'empty.sql' END AS T_REWARDS_SIX_FLAGS_ITEM 
FROM DBA_TABLES
WHERE TABLE_NAME = 'T_REWARDS_SIX_FLAGS_ITEM';

-- Check Sequence for Six Flags Item
SELECT CASE WHEN MAX(SEQUENCE_NAME) IS NULL THEN 'SEQ_REWARDS_SIX_FLAGS_ITEM.sql' ELSE 'empty.sql' END AS SEQ_REWARDS_SIX_FLAGS_ITEM 
FROM DBA_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_REWARDS_SIX_FLAGS_ITEM';

-- Check Table for Six Flags Item Code
SELECT CASE WHEN MAX(TABLE_NAME) IS NULL THEN 'T_REWARDS_SIX_FLAGS_ITEM_CODE.sql' ELSE 'empty.sql' END AS T_REWARDS_SF_ITEM_CODE 
FROM DBA_TABLES
WHERE TABLE_NAME = 'T_REWARDS_SIX_FLAGS_ITEM_CODE';

-- Check Sequence for Six Flags Item Code
SELECT CASE WHEN MAX(SEQUENCE_NAME) IS NULL THEN 'SEQ_REWARDS_SIX_FLAGS_ITEM_CODE.sql' ELSE 'empty.sql' END AS SEQ_REWARDS_SF_ITEM_CODE 
FROM DBA_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_REWARDS_SIX_FLAGS_ITEM_CODE';

-- Check Table for columns in Rewards Redemption History
SELECT CASE WHEN COUNT(1) = 0 THEN 'ALTER_T_REWARD_REDEMPTION_HISTORY_RO.sql' ELSE 'empty.sql' END AS ALTER_T_RWRD_RED_HISTORY 
FROM DBA_TAB_COLS 
where TABLE_NAME = 'T_REWARD_REDEMPTION_HISTORY' and (upper(column_name)='PARTNER_REDEMPTION_ITEM_ID' or 
upper(column_name)='REDEMPTION_TIME' or upper(column_name) = 'ORDER_CONFIRMATION' or upper(column_name) = 'CLIENT_NUMBER' or upper(column_name)='EMAIL_SEND_DATE' 
or upper(column_name)='PARTNER_REDEMPTION_ITEM_CODE_ID' or upper(column_name)='WEB_PRESENT_CODE' or 
upper(column_name)='REDEEMER_EMAIL_1' or upper(column_name)='NOTIFICATION_ID');

-- Check Table for columns in Rewards Redemption History Pending
SELECT CASE WHEN COUNT(1) = 0 THEN 'ALTER_T_RWRD_REDEMPTION_PENDING_RO.sql' ELSE 'empty.sql' END AS ALTER_T_REWARD_RED_PENDING 
FROM DBA_TAB_COLS
where TABLE_NAME = 'T_RWRD_REDEMPTION_PENDING' and (upper(column_name)='SUPPLIER_GOODS_ID' or 
upper(column_name)='REDEMPTION_TIME' or upper(column_name) = 'ORDER_CONFIRMATION' or upper(column_name) = 'CLIENT_NUMBER' or upper(column_name)='WEB_PRESENT_CODE' 
or upper(column_name)='REDEEMER_EMAIL_1');

-- Check Table for Lookup Offer Type
SELECT CASE WHEN MAX(TABLE_NAME) IS NULL THEN 'T_LU_REWARDS_OFFER_TYPE.sql' ELSE 'empty.sql' END AS T_LU_REWARDS_OFFER_TYPE 
FROM DBA_TABLES
WHERE TABLE_NAME = 'T_LU_REWARDS_OFFER_TYPE';

-- Check Sequence for Lookup Offer Type
SELECT CASE WHEN MAX(SEQUENCE_NAME) IS NULL THEN 'SEQ_LU_REWARDS_OFFER_TYPE.sql' ELSE 'empty.sql' END AS SEQ_LU_REWARDS_OFFER_TYPE 
FROM DBA_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_LU_REWARDS_OFFER_TYPE';

DECLARE

  V_T_REWARDS_SF_ITEM 			VARCHAR(256);
  V_SEQ_REWARDS_SF_ITEM 			VARCHAR(256);
  
  V_T_REWARDS_SF_ITEM_CODE 		VARCHAR(256);
  V_SEQ_RWRDS_SF_ITEM_CODE 	VARCHAR(256);
  
  V_ALTER_T_RWRD_RED_HISTORY		VARCHAR(256);
  V_ALTER_T_REWARD_RED_PENDING 	VARCHAR(256);
  
  V_T_LU_RWRDS_OFFER_TYPE 			VARCHAR(256);
  V_SEQ_LU_RWRDS_OFFER_TYPE 			VARCHAR(256);
BEGIN 
  
  -- Add Table for Six Flags Item
  V_T_REWARDS_SF_ITEM := '&&_T_REWARDS_SIX_FLAGS_ITEM';
  IF V_T_REWARDS_SF_ITEM = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('Table T_REWARDS_SIX_FLAGS_ITEM already exists. Skipped.');
  END IF;
  
  -- Add Sequence for Six Flags Item
  V_SEQ_REWARDS_SF_ITEM := '&&_SEQ_REWARDS_SIX_FLAGS_ITEM';
  IF V_SEQ_REWARDS_SF_ITEM = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('Sequence SEQ_REWARDS_SIX_FLAGS_ITEM already exists. Skipped.');
  END IF;
  
  -- Add Table for Six Flags Item Code
  V_T_REWARDS_SF_ITEM_CODE := '&&_T_REWARDS_SF_ITEM_CODE';
  IF V_T_REWARDS_SF_ITEM_CODE = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('Table T_REWARDS_SIX_FLAGS_ITEM_CODE already exists. Skipped.');
  END IF;
  
  -- Add Sequence for Six Flags Item Code
  V_SEQ_RWRDS_SF_ITEM_CODE := '&&_SEQ_RWRDS_SF_ITEM_CODE';
  IF V_SEQ_RWRDS_SF_ITEM_CODE = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('Sequence SEQ_REWARDS_SIX_FLAGS_ITEM_CODE already exists. Skipped.');
  END IF;
  
  -- Alter Table for Rewards Redemption History
  V_ALTER_T_RWRD_RED_HISTORY := '&&_ALTER_T_RWRD_RED_HISTORY';
  IF V_ALTER_T_RWRD_RED_HISTORY = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('New columns already exists in T_REWARD_REDEMPTION_HISTORY. Skipped.');
  END IF;
  
  -- Alter Table for Rewards Redemption History Pending
  V_ALTER_T_REWARD_RED_PENDING := '&&_ALTER_T_REWARD_RED_PENDING';
  IF V_ALTER_T_REWARD_RED_PENDING = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('New columns already exists in T_RWRD_REDEMPTION_PENDING. Skipped.');
  END IF;
  
  -- Add Table for Lookup Offer Type
  V_T_LU_RWRDS_OFFER_TYPE := '&&_T_LU_REWARDS_OFFER_TYPE';
  IF V_T_LU_RWRDS_OFFER_TYPE = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('Table T_LU_REWARDS_OFFER_TYPE already exists. Skipped.');
  END IF;
  
  -- Add Sequence for Lookup Offer Type
  V_SEQ_LU_RWRDS_OFFER_TYPE := '&&_SEQ_LU_REWARDS_OFFER_TYPE';
  IF V_SEQ_LU_RWRDS_OFFER_TYPE = 'empty.sql' THEN
    DBMS_OUTPUT.PUT_LINE('Sequence SEQ_LU_REWARDS_OFFER_TYPE already exists. Skipped.');
  END IF;
  
END;
/

@&_T_LU_REWARDS_OFFER_TYPE
sho ERRORS;

@&_SEQ_LU_REWARDS_OFFER_TYPE
sho ERRORS;

@&_T_REWARDS_SIX_FLAGS_ITEM
sho ERRORS;

@&_SEQ_REWARDS_SIX_FLAGS_ITEM
sho ERRORS;

@&_T_REWARDS_SF_ITEM_CODE
sho ERRORS;

@&_SEQ_RWRDS_SF_ITEM_CODE
sho ERRORS;

@&_ALTER_T_RWRD_RED_HISTORY
sho ERRORS;

@&_ALTER_T_REWARD_RED_PENDING
sho ERRORS; 

SELECT TO_CHAR(SYSDATE, 'DD-Mon-YYYY HH24:MI:SS') date_
  FROM dual;

sho ERRORS 
spo OFF
/
