/*
  Script:      310_DBAatCAS_MK1050_SYN_RO.sql
  Author:      fmassarini
  Date:        02/09/2021
  Purpose:     Create synonyms for tables accessed through DBLink. Required for compilation of Six Flags notification processing PKG.
*/

SET TERMOUT ON
SET ECHO OFF
SET LINESIZE 80
SET SERVEROUTPUT ON SIZE 10000
WHENEVER SQLERROR EXIT ROLLBACK
column filename NEW_VAL filename1 

SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME')     filename
  FROM dual; 
  
spo 310_DBAatCAS_MK1050_SYN_RO_&filename1..log

ALTER SESSION SET EDITION = ORA$BASE;

SELECT 'current user is ' || USER || ' at ' FROM dual;
 
SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

/* *** */

DECLARE
  v_user_env VARCHAR2(20);
  v_dblink VARCHAR2(30);
BEGIN
    SELECT LOWER(SYS_CONTEXT('USERENV', 'DB_NAME')) INTO v_user_env FROM dual;

	IF v_user_env =  'cas'  THEN
	    v_dblink := 'OPSREWARD.US.ORACLE.COM';
	ELSE
	    v_dblink := 'OPSREWARD.FNBM.CORP';
	END IF;
	
	EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM T_REWARDS_SIX_FLAGS_ITEM FOR REWARD.T_REWARDS_SIX_FLAGS_ITEM@' || v_dblink;
	EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM T_REWARDS_SIX_FLAGS_ITEM_CODE FOR REWARD.T_REWARDS_SIX_FLAGS_ITEM_CODE@' || v_dblink;
	EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM T_LU_REWARDS_OFFER_TYPE FOR REWARD.T_LU_REWARDS_OFFER_TYPE@' || v_dblink;
END;
/

GRANT UPDATE ON CUSTOMER.CHD_PROCESS_LOG_01 TO NOTIFY;

/* *** */

SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

sho ERRORS
spo OFF
