/*
  Script:      600_DBAatCAS_MK1050_SYN_RO.sql
  Author:      Levi Tamiozzo
  Date:        2020-11-17
  Purpose:     Update pkg synonym + grant select on account tables.
*/

SET TERMOUT ON
SET ECHO OFF
SET LINESIZE 80
spool off
SET SERVEROUTPUT ON SIZE 10000
WHENEVER SQLERROR EXIT ROLLBACK
column filename NEW_VAL filename1 

SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME')  filename
  FROM dual;

spo 600_DBAatCAS_MK1050_SYN_RO_&filename1..log;

ALTER SESSION SET EDITION = ORA$BASE;

SELECT 'current user is ' || USER || ' at ' FROM dual;
 
SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

/* SQL Statement Start */

CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM PKG_FDR_REWARDS_STAGING FOR ODS_STG.PKG_FDR_REWARDS_STAGING_P;

CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM Pkg_T_Rt FOR IFLOW.Pkg_T_Rt_P;

CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM pkg_coll_account_info FOR COLL.pkg_coll_account_info_p;

CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM PKG_NOTIFY_SIXFLAGS FOR NOTIFY.PKG_NOTIFY_SIXFLAGS_P;

/* SQL Statement End */

SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

sho ERRORS
spo OFF
