ALTER TABLE 
   T_RWRD_REDEMPTION_PENDING 
ADD
   (
	SUPPLIER_GOODS_ID			VARCHAR2(50) 											NULL,
    REDEMPTION_TIME				VARCHAR2(6)  											NULL,
	ORDER_CONFIRMATION			VARCHAR2(30) 											NULL,
	CLIENT_NUMBER				VARCHAR2(4) 											NULL,
	WEB_PRESENT_CODE			VARCHAR2(8)	  											NULL,
	REDEEMER_EMAIL_1			VARCHAR2(50)  											NULL
   );