ALTER TABLE 
   T_REWARD_REDEMPTION_HISTORY 
ADD
(
    PARTNER_REDEMPTION_ITEM_ID		NUMBER			NULL,
    REDEMPTION_TIME					VARCHAR2(6)  	NULL,
	ORDER_CONFIRMATION				VARCHAR2(30)	NULL,
	CLIENT_NUMBER					VARCHAR2(4)		NULL,
	EMAIL_SEND_DATE					DATE	NULL,
    PARTNER_REDEMPTION_ITEM_CODE_ID	NUMBER  NULL,
	WEB_PRESENT_CODE				VARCHAR2(8)	 NULL,
	REDEEMER_EMAIL_1				VARCHAR2(50)  NULL,
	NOTIFICATION_ID					NUMBER NULL
);