/*
  Script:      INSERT_EMAIL_REDEM_INTO_T_LU_NOTIFICATION_TEMPLATE.sql
  Schema:      NOTIFY
  Author:      Levi Tamiozzo
  Project:     MK-1050
  Date:        2021-02-04
  Purpose:     Insert templates for Six Flags REDEM Emails.
*/

DECLARE

    V_COUNT NUMBER;
	
	TYPE REC_TYPE IS RECORD(
		REC_TMPL_CODE 			T_LU_NOTIFICATION_TEMPLATE.NOTIFICATION_TMPL_CODE%TYPE,
		REC_TMPL_TYPE_CODE 		T_LU_NOTIFICATION_TEMPLATE.NOTIFICATION_TMPL_TYPE_CODE%TYPE,
		REC_TEMPLATE_BODY 		T_LU_NOTIFICATION_TEMPLATE.TEMPLATE_BODY%TYPE,
		REC_IS_ACTIVE   		T_LU_NOTIFICATION_TEMPLATE.IS_ACTIVE%TYPE						DEFAULT 1,
		REC_C1B_TEMPLATE_NAME	T_LU_NOTIFICATION_TEMPLATE.C1B_TEMPLATE_NAME%TYPE,
		REC_TRANS_TYPE_CODE 	T_LU_NOTIFICATION_TEMPLATE.NOTIFICATION_TRANS_TYPE_CODE%TYPE 	DEFAULT 'EMAILEXTERNAL',
		REC_COMM_CHANNEL_CODE  	T_LU_NOTIFICATION_TEMPLATE.COMM_CHANNEL_CODE%TYPE 				DEFAULT 'MKT_EMAILS'
    );	
		
	TYPE LIST_TYPE IS TABLE OF REC_TYPE INDEX BY PLS_INTEGER;
	
    V_LIST LIST_TYPE;

BEGIN		      

	V_LIST(1).REC_TMPL_CODE 		:= '364467';
	V_LIST(1).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGS12MMEMB';
	V_LIST(1).REC_C1B_TEMPLATE_NAME := 'ME070741';
	
	V_LIST(2).REC_TMPL_CODE 		:= '364582';
	V_LIST(2).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSSSNPASS';
	V_LIST(2).REC_C1B_TEMPLATE_NAME := 'ME070744';
	
	V_LIST(3).REC_TMPL_CODE 		:= '364585';
	V_LIST(3).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSDAYPASS';
	V_LIST(3).REC_C1B_TEMPLATE_NAME := 'ME070747';
	
	V_LIST(4).REC_TMPL_CODE 		:= '364466';
	V_LIST(4).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSDXDINEPASS';
	V_LIST(4).REC_C1B_TEMPLATE_NAME := 'ME070742';
	
	V_LIST(5).REC_TMPL_CODE 		:= '364583';
	V_LIST(5).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSANDINEPASS';
	V_LIST(5).REC_C1B_TEMPLATE_NAME := 'ME070740';
	
	V_LIST(6).REC_TMPL_CODE 		:= '364561';
	V_LIST(6).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSSSNDRINK';
	V_LIST(6).REC_C1B_TEMPLATE_NAME := 'ME070739';
	
	V_LIST(7).REC_TMPL_CODE 		:= '364505';
	V_LIST(7).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSDAYDRINK';
	V_LIST(7).REC_C1B_TEMPLATE_NAME := 'ME070738';
	
	V_LIST(8).REC_TMPL_CODE 		:= '364601';
	V_LIST(8).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSDAYDINE';
	V_LIST(8).REC_C1B_TEMPLATE_NAME := 'ME070745';
	
	V_LIST(9).REC_TMPL_CODE 		:= '364581';
	V_LIST(9).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSDAYFLASH';
	V_LIST(9).REC_C1B_TEMPLATE_NAME := 'ME070743';
	
	V_LIST(10).REC_TMPL_CODE 		:= '364584';
	V_LIST(10).REC_TMPL_TYPE_CODE 	:= 'SIXFLAGSPARKING';
	V_LIST(10).REC_C1B_TEMPLATE_NAME := 'ME070746';	
  	
	FOR I IN V_LIST.FIRST .. V_LIST.LAST LOOP 
		
		-- Check if the template already exists. 
		SELECT COUNT(1)
		  INTO V_COUNT
		  FROM T_LU_NOTIFICATION_TEMPLATE T
		 WHERE T.NOTIFICATION_TMPL_CODE = V_LIST(I).REC_TMPL_CODE;

		-- Insert it if it doesn't.
		IF V_COUNT = 0 THEN
			INSERT INTO T_LU_NOTIFICATION_TEMPLATE
				(NOTIFICATION_TMPL_CODE,
				 NOTIFICATION_TMPL_TYPE_CODE,
				 NOTIFICATION_TRANS_TYPE_CODE,
				 TEMPLATE_BODY,
				 IS_ACTIVE,
				 C1B_TEMPLATE_NAME,
				 COMM_CHANNEL_CODE)
			VALUES
				(V_LIST(I).REC_TMPL_CODE,
				 V_LIST(I).REC_TMPL_TYPE_CODE,
				 V_LIST(I).REC_TRANS_TYPE_CODE,
				 V_LIST(I).REC_TEMPLATE_BODY,
				 V_LIST(I).REC_IS_ACTIVE,
				 V_LIST(I).REC_C1B_TEMPLATE_NAME,
				 V_LIST(I).REC_COMM_CHANNEL_CODE);
		  
			DBMS_OUTPUT.PUT_LINE('Template '''|| V_LIST(I).REC_TMPL_CODE ||''' created succesfuly.');
		ELSE                                                   
			DBMS_OUTPUT.PUT_LINE('Template '''|| V_LIST(I).REC_TMPL_CODE ||''' already exists, skipped.');
		END IF;	  
	  
	END LOOP;
	
	COMMIT;
    
END;
/