/*
  Script:      INSERT_EMAIL_REDEM_INTO_T_LU_NOTIFICATION_TMPL_VAR.sql
  Schema:      NOTIFY
  Author:      Levi Tamiozzo
  Project:     MK-1050
  Date:        2021-02-04
  Purpose:     Insert template variables for Six Falgs REDEM Emails.
*/

DECLARE

    V_COUNT NUMBER;
	
	TYPE VAR_TYPE IS RECORD(
		REC_VARIABLE_NAME	T_LU_NOTIFICATION_TMPL_VAR.VARIABLE_NAME%TYPE,
		REC_IS_REPEATABLE   T_LU_NOTIFICATION_TMPL_VAR.IS_REPEATABLE%TYPE DEFAULT 0
    );	
	
	TYPE VAR_LIST_TYPE IS TABLE OF VAR_TYPE INDEX BY PLS_INTEGER;
	
	V_VAR_LIST VAR_LIST_TYPE;
	
	TYPE TMPL_TYPE IS RECORD(
		REC_TMPL_CODE 				T_LU_NOTIFICATION_TMPL_VAR.NOTIFICATION_TMPL_CODE%TYPE,		
		REC_HAS_OPERATING_SEASON	NUMBER(1) DEFAULT 1
    );

	TYPE TMPL_LIST_TYPE IS TABLE OF TMPL_TYPE INDEX BY PLS_INTEGER;
	
    V_TMPL_LIST TMPL_LIST_TYPE;

BEGIN		      

	V_TMPL_LIST(1).REC_TMPL_CODE 	:= '364467';	
	V_TMPL_LIST(2).REC_TMPL_CODE 	:= '364582';
	V_TMPL_LIST(3).REC_TMPL_CODE 	:= '364585';
	V_TMPL_LIST(4).REC_TMPL_CODE 	:= '364466';	
	V_TMPL_LIST(5).REC_TMPL_CODE 	:= '364583';
	V_TMPL_LIST(6).REC_TMPL_CODE 	:= '364561';
	V_TMPL_LIST(7).REC_TMPL_CODE 	:= '364505';
	V_TMPL_LIST(8).REC_TMPL_CODE 	:= '364601';
	V_TMPL_LIST(9).REC_TMPL_CODE	:= '364581';
	V_TMPL_LIST(10).REC_TMPL_CODE 	:= '364584';

	V_VAR_LIST(1).REC_VARIABLE_NAME := 'FIRSTNAME';
	V_VAR_LIST(2).REC_VARIABLE_NAME := 'LASTNAME';
	V_VAR_LIST(3).REC_VARIABLE_NAME := 'CARDTYPE';
	V_VAR_LIST(4).REC_VARIABLE_NAME := 'CARDLASTFOUR';
	V_VAR_LIST(5).REC_VARIABLE_NAME := 'MISCELLANEOUS10'; --'POINTSREDEEMED';
	V_VAR_LIST(6).REC_VARIABLE_NAME := 'MISCELLANEOUS11'; --'PARKNAME';
	V_VAR_LIST(7).REC_VARIABLE_NAME := 'MISCELLANEOUS12'; --'ITEMDESCRIPTION';
	V_VAR_LIST(8).REC_VARIABLE_NAME := 'MISCELLANEOUS13'; --'BARCODE';
	V_VAR_LIST(9).REC_VARIABLE_NAME := 'MISCELLANEOUS17'; --'REDEMPTIONDATE';
	V_VAR_LIST(10).REC_VARIABLE_NAME := 'MISCELLANEOUS18'; --'OPERATINGSEASON (YYYY)';
  	
	FOR I IN V_TMPL_LIST.FIRST .. V_TMPL_LIST.LAST LOOP 
		
		FOR J IN V_VAR_LIST.FIRST .. V_VAR_LIST.LAST LOOP 
		
			-- Check if the template var already exists. 
			SELECT COUNT(1)
			  INTO V_COUNT
			  FROM T_LU_NOTIFICATION_TMPL_VAR T
			 WHERE T.NOTIFICATION_TMPL_CODE = V_TMPL_LIST(I).REC_TMPL_CODE
			   AND T.VARIABLE_NAME = V_VAR_LIST(J).REC_VARIABLE_NAME;

			-- Insert it if it doesn't.
			IF V_COUNT = 0 THEN
			
				IF (V_VAR_LIST(J).REC_VARIABLE_NAME != 'MISCELLANEOUS18' OR V_TMPL_LIST(I).REC_HAS_OPERATING_SEASON = 1) THEN
					
					INSERT INTO T_LU_NOTIFICATION_TMPL_VAR
						(NOTIFICATION_TMPL_CODE,
						 VARIABLE_NAME,
						 IS_REPEATABLE)
					VALUES
						(V_TMPL_LIST(I).REC_TMPL_CODE,
						 V_VAR_LIST(J).REC_VARIABLE_NAME,
						 V_VAR_LIST(J).REC_IS_REPEATABLE);
					
					DBMS_OUTPUT.PUT_LINE('Template var '''|| V_VAR_LIST(J).REC_VARIABLE_NAME ||''' for template code '''|| V_TMPL_LIST(I).REC_TMPL_CODE ||''' created succesfuly.');				
				END IF;		
				
			ELSE                                                   
				DBMS_OUTPUT.PUT_LINE('Template var '''|| V_VAR_LIST(J).REC_VARIABLE_NAME ||''' for template code '''|| V_TMPL_LIST(I).REC_TMPL_CODE ||''' already exists, skipped.');  			
			END IF;	  
	  
		END LOOP;
	  
	END LOOP;
	
	COMMIT;
    
END;
/
