/* Create Table */

CREATE TABLE  T_LU_REWARDS_OFFER_TYPE
(
  ID                  NUMBER        CONSTRAINT NN_REW_OFFER_TYPE_ID  NOT NULL,
  NAME  VARCHAR2(50)  CONSTRAINT NN_REW_OFFER_TYPE_NAME     NOT NULL,
  TEMPLATE_TYPE_CODE	VARCHAR2(20) CONSTRAINT NN_REW_OFFER_TYPE_TMPL_TYPE_C  NOT NULL
)
TABLESPACE REWARD_D;


/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE T_LU_REWARDS_OFFER_TYPE 
  ADD CONSTRAINT PK_T_LU_REWARDS_OFFER_TYPE
  PRIMARY KEY
  (ID);

ALTER TABLE T_LU_REWARDS_OFFER_TYPE
ADD CONSTRAINT OFFER_TYPE_NAME_UNIQUE UNIQUE (NAME);
