/* Create Table */

CREATE TABLE  T_REWARDS_SIX_FLAGS_ITEM
(
  ID                		NUMBER        	CONSTRAINT NN_REW_SIX_FLAGS_ITEM_ID  				NOT NULL,
  ITEM_ID 					VARCHAR2(50)  	CONSTRAINT NN_REW_SIX_FLAGS_ITEM_ITEM_ID  			NOT NULL,
  OFFER_NAME				VARCHAR2(100)	CONSTRAINT NN_REW_SIX_FLAGS_ITEM_OFFER_NAME			NOT NULL,
  PARK_NAME  				VARCHAR2(1000)  	CONSTRAINT NN_REW_SIX_FLAGS_ITEM_PARK_NAME  		NOT NULL,
  LOW_VOLUME_THRESHOLD		NUMBER  		CONSTRAINT NN_REW_SIX_FLAGS_ITEM_LOW_VOL_THRES  	NOT NULL,
  IS_ACTIVE 				NUMBER(1)  		CONSTRAINT NN_REW_SIX_FLAGS_ITEM_IS_ACTIVE			NOT NULL,
  OFFER_TYPE_ID  NUMBER   	DEFAULT 1 NOT NULL,
  STATUS_CHANGED_DATE		DATE
)
TABLESPACE REWARD_D;
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

CREATE INDEX IX_RSFI_STATUS_CHANGE_DATE ON T_REWARDS_SIX_FLAGS_ITEM
(TRUNC(STATUS_CHANGED_DATE)) TABLESPACE REWARD_I;

ALTER TABLE T_REWARDS_SIX_FLAGS_ITEM 
  ADD CONSTRAINT PK_T_REWARDS_SIX_FLAGS_ITEM
  PRIMARY KEY
  (ID);

ALTER TABLE T_REWARDS_SIX_FLAGS_ITEM
	ADD CONSTRAINT ITEM_ID_UNIQUE UNIQUE (ITEM_ID);
	
ALTER TABLE T_REWARDS_SIX_FLAGS_ITEM
  ADD CONSTRAINT FK_T_REWARDS_SIX_FLAGS_ITEM_T_LU_REW_OFFER_TYPE
	FOREIGN KEY (OFFER_TYPE_ID) REFERENCES T_LU_REWARDS_OFFER_TYPE (ID);
