CREATE OR REPLACE VIEW REPORTER.V_REWARDS_SIX_FLAGS
(
	SEQUENCE_ID,
	CLIENT_NUMBER,
	SYSTEM_CODE,
	PRIN_CODE,
	AGENT_CODE,
	CREDIT_ACCOUNT_ID,
	CARD_ID,
	OLD_ACCOUNT_ID,
	FISERV_REDEMPTION_DATE,
	C1B_PROCESSED_DATE,
	ORDER_CONFIRMATION,
	WEB_PRESENT_CODE,
	VENDOR_NAME,
	ITEM_ID,
	BARCODE,
	POINTS_REDEEMED,
	REWARD_EXPIRATION_DATE
)
AS
   SELECT rh.REDEMPTION_HISTORY_ID AS SEQUENCE_ID,
       rh.CLIENT_NUMBER,
       s.SYSTEM_CODE,
       s.PRIN_CODE,
       s.AGENT_CODE,
       rh.CREDIT_ACCOUNT_ID,
       rh.CARD_ID,
	   c.OLD_ACCOUNT_ID,
       rh.REDEMPTION_DATE,
       rh.EMAIL_SEND_DATE,
       rh.ORDER_CONFIRMATION,
       rh.WEB_PRESENT_CODE,
       DECODE(rh.WEB_PRESENT_CODE,
              'PLPCRD02',
              'SIX FLAGS',
              'PLPCRD01',
              'WANDER') AS VENDOR_NAME,
       rh.PARTNER_REDEMPTION_ITEM_ID AS ITEM_ID,
       sfic.CODE AS BARCODE,
       DECODE(POINTS_REDEEMED_SIGN,
              '+', POINTS_REDEEMED,
              '-', -1 * POINTS_REDEEMED) as POINTS_REDEEMED,
       '' as REWARD_EXPIRATION_DATE
  FROM T_REWARD_REDEMPTION_HISTORY rh
 INNER JOIN T_CARD c
    ON (rh.CARD_ID = c.CARD_ID)
 INNER JOIN T_LU_SPA s
    ON (c.SPA_ID = s.SPA_ID)
 INNER JOIN T_REWARDS_SIX_FLAGS_ITEM_CODE sfic
    ON (rh.PARTNER_REDEMPTION_ITEM_CODE_ID = sfic.ID);
