/*
  Script:      600_DBAatCAS_MK1050_SYN_RB.sql
  Author:      Levi Tamiozzo
  Date:        2020-11-17
  Purpose:     Rollback pkg synonym.
*/

SET TERMOUT ON
SET ECHO OFF
SET LINESIZE 80

SET SERVEROUTPUT ON SIZE 10000
WHENEVER SQLERROR EXIT ROLLBACK
column filename NEW_VAL filename1 

SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME')  filename
  FROM dual;

spo 600_DBAatCAS_MK1050_SYN_RB_&filename1..log;

ALTER SESSION SET EDITION = ORA$BASE;

SELECT 'current user is ' || USER || ' at ' FROM dual;

SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

/* SQL Statement Start */

BEGIN
 EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM PKG_FDR_REWARDS_STAGING FOR ODS_STG.PKG_FDR_REWARDS_STAGING_R';
EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM Pkg_T_Rt FOR IFLOW.Pkg_T_Rt_R';

EXECUTE IMMEDIATE 'REVOKE SELECT ON ACCOUNT.T_LU_PRODUCT_GROUP_PROGRAM FROM IFLOW';
EXECUTE IMMEDIATE 'REVOKE SELECT ON ACCOUNT.T_LU_PRODUCT_GROUP FROM IFLOW';

EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM pkg_coll_account_info FOR COLL.pkg_coll_account_info_r';

EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM PKG_NOTIFY_SIXFLAGS';

END;
/

/* SQL Statement End */

SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

sho ERRORS
spo OFF
