/*
  Script:      700_DBAatOPS_MK1050_SYN_RB.sql
  Author:      Levi Tamiozzo
  Date:        01/26/2021
*/

SET TERMOUT ON
SET ECHO OFF
SET LINESIZE 80
SET SERVEROUTPUT ON SIZE 1040040
WHENEVER SQLERROR EXIT ROLLBACK
column filename new_val filename1 

SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME')  filename
  FROM dual;
  
spo 700_DBAatOPS_MK1050_SYN_RB_&filename1..log; 
 
SELECT 'current user is ' || USER || ' at ' FROM dual;

SELECT SYS_CONTEXT('USERENV','INSTANCE_NAME') FROM dual;
 
SELECT TO_CHAR(SYSDATE,'DD-Mon-YYYY HH24:MI:SS') date_ FROM dual;

/* SQL Statements Start */

DECLARE

  V_COUNT NUMBER;
  
BEGIN  
 EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE PUBLIC SYNONYM PKG_MS_REWARDS_SUMMARY FOR REWARD.PKG_MS_REWARDS_SUMMARY_R';
 
  -- Drop Synonym PKG_MS_REWARDS_SIX_FLAGS_ITEM
  SELECT COUNT(1)
    INTO V_COUNT 
    FROM DBA_OBJECTS T
   WHERE T.OBJECT_TYPE = 'SYNONYM'
     AND T.OBJECT_NAME = 'PKG_MS_REWARDS_SIX_FLAGS_ITEM';
  
  IF (V_COUNT > 0) THEN 
     EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM PKG_MS_REWARDS_SIX_FLAGS_ITEM';
  END IF; 

-- Drop Synonym PKG_MS_REWARDS_SIX_FLAGS_ITEM
  SELECT COUNT(1)
    INTO V_COUNT 
    FROM DBA_OBJECTS T
   WHERE T.OBJECT_TYPE = 'SYNONYM'
     AND T.OBJECT_NAME = 'PKG_MS_REWARDS_OFFER_TYPE';
  
  IF (V_COUNT > 0) THEN 
     EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM PKG_MS_REWARDS_OFFER_TYPE';
  END IF;  
  
END;
/

/* SQL Statements Start End */

SELECT TO_CHAR(SYSDATE, 'DD-Mon-YYYY HH24:MI:SS') date_
  FROM dual;

sho ERRORS 
spo OFF
